### ISSUE TITLE
Follow best security practises

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-desktop#15]
Right now we have the minimum which is `nodeIntegration` set to `false`, but it'd be great to follow https://electronjs.org/docs/tutorial/security and make sure we follow the best practices.

**Comment by onbjerg** [comment]
Best Practices, A List:

- [ ] [Enable Context Isolation for Remote Content](https://electronjs.org/docs/tutorial/security#3-enable-context-isolation-for-remote-content): Run preload scripts in a dedicated Javascript context. Preload scripts still have access to `window` (which is needed for at least #27).
- [ ] [Define a Content Security Policy](https://electronjs.org/docs/tutorial/security#6-define-a-content-security-policy)
- [ ] [Only load secure content](https://electronjs.org/docs/tutorial/security#1-only-load-secure-content): Prefer https/wss over http/ws
- [x] [Disable Node.js Integration for Remote Content](https://electronjs.org/docs/tutorial/security#2-disable-nodejs-integration-for-remote-content)

These are the ones that are currently relevant to Aragon Desktop. The others do not apply, e.g. the one about not enabling experimental features - this is not being done right now, so no worry to be had there :)
